server:
  port: 8762

spring:
  application:
    name: eureka-server #应用名称


eureka:
  server:
    enable-self-preservation: true #true开启自我保护模式 false关闭
    eviction-interval-timer-in-ms: 60000  #清理间隔 单位毫秒 默认60*1000ms
  instance:
    hostname: eureka02 #主机名,不配置的时候将根据操作系统的主机名来获取
    prefer-ip-address: true #是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #ip:port
  client:
#    register-with-eureka: false  #是否将自己注册到注册中心,默认为true 单节点false
#    fetch-registry: false  #是否从注册中心获取服务注册信息,默认为true
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:8761/eureka/